name: iOS Build (Free Developer Account)

on:
  workflow_dispatch: # Exécution manuelle uniquement

jobs:
  build:
    name: Build iOS App with Free Account
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          
      - name: Install dependenciesqEn
        run: npm install
        
      - name: Generate native iOS files
        run: npx expo prebuild -p ios
        
      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install
          
      # Connexion automatique avec votre Apple ID
      - name: Setup free Apple Developer account
        env:
          APPLE_ID_USERNAME: ${{ secrets.APPLE_ID_USERNAME }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
        run: |
          cd ios
          xcrun xcodebuild -allowProvisioningUpdates \
            -workspace sallesavignon.xcworkspace \
            -scheme sallesavignon \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            build
            
      - name: Archive build products
        uses: actions/upload-artifact@v4
        with:
          name: ios-simulator-build
          path: ios/build/